model_params:
  name: 'ConditionalVAE'
  in_channels: 3
  num_classes: 2 # Updated to 2 for Chest X-Ray dataset (Normal, Pneumonia)
  latent_dim: 128

data_params:
  data_path: "Data/chest_xray/"
  train_batch_size: 64
  val_batch_size:  64
  patch_size: 64
  num_workers: 4


exp_params:
  LR: 0.005
  weight_decay: 0.0
  scheduler_gamma: 0.95
  kld_weight: 0.00025
  manual_seed: 1265

trainer_params:
  max_epochs: 10
  min_epochs: 1
  num_sanity_val_steps: 2
  gradient_clip_val: 0.5

logging_params:
  save_dir: "logs/"
  name: "ConditionalVAE"
  monitor_metric: "val_loss"
  save_top_k: 2
  mode: "min"
